### ISSUE TITLE
Option to set `finalize=True` in `_get_or_render_metadata`

### ISSUE THREAD

**Issue by isuruf** [conda/conda-concourse-ci#70]
I can send a PR. Should `finalize` be passed around?

**Comment by msarahan** [comment]
That's a private function.  Yes, finalize should be passed through to it, but no, you're not really meant to directly call that function.

Part of making c3i a public-facing package will be defining its API.  I'll start a separate issue for that.  We need to come up with user stories / use cases for what we want c3i to be able to help with.  It's important that we limit the public functionality as much as possible to maintain future stability.  That has been a major headache with conda and conda-build - let's see if we can do better at the start here.

**Comment by msarahan** [comment]
issue for "public API" at https://github.com/conda/conda-concourse-ci/issues/71
